# Generated by Django 5.1.1 on 2024-10-04 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_panel', models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('name_panel', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('inbound', models.TextField(null=True)),
                ('proxies', models.TextField(null=True)),
            ],
            options={
                'unique_together': {('name_panel',)},
            },
        ),
    ]
