# Generated by Django 5.1.1 on 2024-10-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_agent', '0003_log_useragent_useragent_account_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='limit_volume',
            field=models.IntegerField(null=True),
        ),
    ]
