# Generated by Django 5.1.1 on 2024-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_agent', '0004_alter_useragent_limit_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='limit_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useragent',
            name='limit_volume',
            field=models.FloatField(null=True),
        ),
    ]
